changelog:
  exclude:
    labels:
      - ignore-for-release
      - tagpr
  categories:
    - title: ⚡ Breaking Changes
      labels:
        - major
        - breaking-change
    - title: ✨ Features
      labels:
        - feature
    - title: 🐛 Bug Fixes
      labels:
        - bug
    - title: 📚 Documentation
      labels:
        - documentation
    - title: CI/CD
      labels:
        - ci-cd
    - title: 🔧 Maintenance
      labels:
        - maintenance
    - title: 👒 Dependencies
      labels:
        - dependencies
    - title: Other Changes
      labels:
        - "*"
